/* EXPOSE_REDUCE.java */
/* FILE GENERATED BY makeamess - DO NOT EDIT */

/* 
    Copyright 2006, Astrophysics Research Institute, Liverpool John Moores University.

    This file is part of NGAT.

    NGAT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    NGAT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NGAT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
package ngat.message.INST_DP;

import ngat.message.base.*;

import java.util.*;
import java.io.*;
/**
 * This command is the reduce commands for all exposure FITS files.
 *
 * <h2>Command Parameters:</h2>
 * <ul>
 * <li><b><i>String</i> filename</b> (inherited from REDUCE).
 * <li><b><i>boolean</i> wcsFit</b> Whether to try to WCS fit the reduced image (used for acquisition).
 * </ul>
 * <h2>Done Parameters:</h2>
 * <ul>
 * <li><b><i>String</i> filename</b> (inherited from REDUCE).
 * <li><b><i>float</i> seeing</b> (in arcsec) (for the brightest object in the frame).
 * <li><b><i>float</i> counts</b> (0 .. 65535) (for the brightest object in the frame).
 * <li><b><i>float</i> xpix</b> (pixels) (for the brightest object in the frame).
 * <li><b><i>float</i> ypix</b> (pixels) (for the brightest object in the frame).
 * <li><b><i>float</i> photometricity</b> (mags of extinction) (only for standards).
 * <li><b><i>float</i> skyBrightness</b> (mags/arcsec&#178;) (estimate of sky brightness).
 * <li><b><i>boolean</i> saturation</b> (true if the frame was saturated).
 * </ul>
 * @see EXPOSE_REDUCE_DONE
 */

public class EXPOSE_REDUCE extends REDUCE implements Serializable
{

/* CONSTANTS */
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id$");

/* ATTRIBUTES */
	/**
	 * Attribute wcsFit of type boolean.
	 */
	private boolean wcsFit;

/* ATTRIBUTE ACCESSORS */
	/**
	 * Method to set wcsFit.
	 * @param in The value to set, of type boolean.
	 */
	public void setWcsFit(boolean in)
	{
		this.wcsFit=in;
	}

	/**
	 * Method to get wcsFit.
	 * @return The method returns the attribute wcsFit.
	 */
	public boolean getWcsFit()
	{
		return this.wcsFit;
	}


/* CONSTRUCTOR */
	/**
	 * Default constructor for EXPOSE_REDUCE.
	 * @param id The message id.
	 */
	public EXPOSE_REDUCE(String id)
	{
		super(id);
	}
}
