PACKAGENAME    = ngat.serial
PACKAGEDIR     = ngat/serial
JAR_FILE       = ngat_serial.jar
DIRS           = arcomess
DIRS_TARGET    = dirs

SRCS           = 
include         $(LT_SRC_HOME)/ngat/Makefile.ngat
#
#   $Author$ 
# $Revision$
#       $Id$
#     $Date: 2013-06-28 10:14:04 $
#  $RCSfile: Makefile,v $
#   $Source: /space/home/eng/cjm/cvs/ngat/serial/Makefile,v $
#      $Log: not supported by cvs2svn $
