include		$(LT_SRC_HOME)/ngat/Makefile.ngat

PACKAGE_DIR     = ngat/net/cil/test
BINDIR 		= $(LT_HOME)/classes/$(PACKAGE_DIR)
DOCSDIR 	= $(LT_DOC_HOME)/ngat/javadocs/$(PACKAGE_DIR)
DOCFLAGS 	= -version -author -private

SRCS = TestServer.java
OBJS = $(SRCS:%.java=$(BINDIR)/%.class)
DOCS = $(SRCS:%.java=$(DOCSDIR)/%.html)


#
# $Log: not supported by cvs2svn $
# Revision 1.3  2002/11/15 14:15:42  je
# *** empty log message ***
#
# Revision 1.2  2002/11/15 11:41:12  cjm
# Changed Makefile.common to Makefile.ngat
#
# Revision 1.1  2002/11/15 11:40:15  cjm
# Initial revision
#
# Revision 0.1  2000/10/16 17:39:24  cjm
# initial revision.
#
#
