package ngat.phase2;
import ngat.phase2.nonpersist.*;

import com.odi.*;
import com.odi.util.*;
import java.lang.reflect.*;
import java.util.*;
import java.io.*;


// Generated by O3J 


public class Comet extends Source implements Serializable {

     // Variables.


     // Constructor.

     public Comet() {this("untitled");}

     public Comet(String name) {
          super(name);
     }

     // Accessors.



     // Descendant Mutators.

     
     // NP -> P Translator.

     public Comet(NPComet npComet) {
          super(npComet);
          Iterator it;
          
          // Recursively call Daughter Translators.

     } // end (NP -> P Translator).
     
     // P -> NP Translator.

     public void stuff(NPComet npComet) {
          super.stuff(npComet);
          Iterator it;
     } // end (P -> NP Translator).
     
     // P -> NP Translator.

     public NPDBObject makeNP() {
          NPComet npComet = new NPComet();
          stuff(npComet);
          return npComet;
     } // end (makeNp).


} // end class def [Comet].
