package ngat.phase2;
import ngat.phase2.nonpersist.*;

import com.odi.*;
import com.odi.util.*;
import java.lang.reflect.*;
import java.util.*;
import java.io.*;


// Generated by O3J 


public class LowResSpecConfig extends SpecConfig implements Serializable {

     // Variables.



     /**  position of the grating if applicable. */
     protected int gratePosn;


     /**  determines if arc should be done before exposure. */
     protected boolean arcBefore;


     /**  determines if arc should be done after exposure. */
     protected boolean arcAfter;

     // Constructor.

     public LowResSpecConfig() {this("untitled");}

     public LowResSpecConfig(String name) {
          super(name);
     }

     // Accessors.



     /** Sets the  position of the grating if applicable .*/
     public void setGratePosn(int in) { this.gratePosn = in;}


     /** Returns the  position of the grating if applicable. */
     public int getGratePosn() { return gratePosn;}


     /** Sets the  determines if arc should be done before exposure .*/
     public void setArcBefore(boolean in) { this.arcBefore = in;}


     /** True if  determines if arc should be done before exposure. */
     public boolean isArcBefore() { return arcBefore;}


     /** Sets the  determines if arc should be done after exposure .*/
     public void setArcAfter(boolean in) { this.arcAfter = in;}


     /** True if  determines if arc should be done after exposure. */
     public boolean isArcAfter() { return arcAfter;}


     // Descendant Mutators.

     
     // NP -> P Translator.

     public LowResSpecConfig(NPLowResSpecConfig npLowResSpecConfig) {
          super(npLowResSpecConfig);
          Iterator it;
          gratePosn = npLowResSpecConfig.getGratePosn();
          arcBefore = npLowResSpecConfig.isArcBefore();
          arcAfter = npLowResSpecConfig.isArcAfter();
          
          // Recursively call Daughter Translators.

     } // end (NP -> P Translator).
     
     // P -> NP Translator.

     public void stuff(NPLowResSpecConfig npLowResSpecConfig) {
          super.stuff(npLowResSpecConfig);
          Iterator it;
          npLowResSpecConfig.setGratePosn(getGratePosn());
          npLowResSpecConfig.setArcBefore(isArcBefore());
          npLowResSpecConfig.setArcAfter(isArcAfter());
     } // end (P -> NP Translator).
     
     // P -> NP Translator.

     public NPDBObject makeNP() {
          NPLowResSpecConfig npLowResSpecConfig = new NPLowResSpecConfig();
          stuff(npLowResSpecConfig);
          return npLowResSpecConfig;
     } // end (makeNp).


} // end class def [LowResSpecConfig].
