package ngat.phase2;
import ngat.phase2.nonpersist.*;

import com.odi.*;
import com.odi.util.*;
import java.lang.reflect.*;
import java.util.*;
import java.io.*;


// Generated by O3J 


public class MajorPlanet extends Source implements Serializable {

     // Variables.


     // Constructor.

     public MajorPlanet() {this("untitled");}

     public MajorPlanet(String name) {
          super(name);
     }

     // Accessors.



     // Descendant Mutators.

     
     // NP -> P Translator.

     public MajorPlanet(NPMajorPlanet npMajorPlanet) {
          super(npMajorPlanet);
          Iterator it;
          
          // Recursively call Daughter Translators.

     } // end (NP -> P Translator).
     
     // P -> NP Translator.

     public void stuff(NPMajorPlanet npMajorPlanet) {
          super.stuff(npMajorPlanet);
          Iterator it;
     } // end (P -> NP Translator).
     
     // P -> NP Translator.

     public NPDBObject makeNP() {
          NPMajorPlanet npMajorPlanet = new NPMajorPlanet();
          stuff(npMajorPlanet);
          return npMajorPlanet;
     } // end (makeNp).


} // end class def [MajorPlanet].
