package ngat.phase2;
import ngat.phase2.nonpersist.*;

import com.odi.*;
import com.odi.util.*;
import java.lang.reflect.*;
import java.util.*;
import java.io.*;


// Generated by O3J 


public class MinorPlanet extends Source implements Serializable {

     // Variables.


     // Constructor.

     public MinorPlanet() {this("untitled");}

     public MinorPlanet(String name) {
          super(name);
     }

     // Accessors.



     // Descendant Mutators.

     
     // NP -> P Translator.

     public MinorPlanet(NPMinorPlanet npMinorPlanet) {
          super(npMinorPlanet);
          Iterator it;
          
          // Recursively call Daughter Translators.

     } // end (NP -> P Translator).
     
     // P -> NP Translator.

     public void stuff(NPMinorPlanet npMinorPlanet) {
          super.stuff(npMinorPlanet);
          Iterator it;
     } // end (P -> NP Translator).
     
     // P -> NP Translator.

     public NPDBObject makeNP() {
          NPMinorPlanet npMinorPlanet = new NPMinorPlanet();
          stuff(npMinorPlanet);
          return npMinorPlanet;
     } // end (makeNp).


} // end class def [MinorPlanet].
