package ngat.phase2;
import ngat.phase2.nonpersist.*;

import com.odi.*;
import com.odi.util.*;
import java.lang.reflect.*;
import java.util.*;
import java.io.*;


// Generated by O3J 


public class MonitorGroup extends Group implements Serializable {

     // Variables.



     /**  date/time observation periods should start. */
     protected long startDate;


     /**  date/time of last observation period. */
     protected long endDate;


     /**  period between observations. */
     protected long period;


     /**  fraction of period during which observation can be allowed. */
     protected float floatFraction;


     /**  record of last successfully observed period number. */
     protected int lastPeriod;

     // Constructor.

     public MonitorGroup() {this("untitled");}

     public MonitorGroup(String name) {
          super(name);
     }

     // Accessors.



     /** Sets the  date/time observation periods should start .*/
     public void setStartDate(long in) { this.startDate = in;}


     /** Returns the  date/time observation periods should start. */
     public long getStartDate() { return startDate;}


     /** Sets the  date/time of last observation period .*/
     public void setEndDate(long in) { this.endDate = in;}


     /** Returns the  date/time of last observation period. */
     public long getEndDate() { return endDate;}


     /** Sets the  period between observations .*/
     public void setPeriod(long in) { this.period = in;}


     /** Returns the  period between observations. */
     public long getPeriod() { return period;}


     /** Sets the  fraction of period during which observation can be allowed .*/
     public void setFloatFraction(float in) { this.floatFraction = in;}


     /** Returns the  fraction of period during which observation can be allowed. */
     public float getFloatFraction() { return floatFraction;}


     /** Sets the  record of last successfully observed period number .*/
     public void setLastPeriod(int in) { this.lastPeriod = in;}


     /** Returns the  record of last successfully observed period number. */
     public int getLastPeriod() { return lastPeriod;}


     // Descendant Mutators.

     
     // NP -> P Translator.

     public MonitorGroup(NPMonitorGroup npMonitorGroup) {
          super(npMonitorGroup);
          Iterator it;
          startDate = npMonitorGroup.getStartDate();
          endDate = npMonitorGroup.getEndDate();
          period = npMonitorGroup.getPeriod();
          floatFraction = npMonitorGroup.getFloatFraction();
          lastPeriod = npMonitorGroup.getLastPeriod();
          
          // Recursively call Daughter Translators.

     } // end (NP -> P Translator).
     
     // P -> NP Translator.

     public void stuff(NPMonitorGroup npMonitorGroup) {
          super.stuff(npMonitorGroup);
          Iterator it;
          npMonitorGroup.setStartDate(getStartDate());
          npMonitorGroup.setEndDate(getEndDate());
          npMonitorGroup.setPeriod(getPeriod());
          npMonitorGroup.setFloatFraction(getFloatFraction());
          npMonitorGroup.setLastPeriod(getLastPeriod());
     } // end (P -> NP Translator).
     
     // P -> NP Translator.

     public NPDBObject makeNP() {
          NPMonitorGroup npMonitorGroup = new NPMonitorGroup();
          stuff(npMonitorGroup);
          return npMonitorGroup;
     } // end (makeNp).
     // handcoded. insert in O2J generated MonitorGroup.java
     
     public ScheduleDescriptor schedule() {return null;}


} // end class def [MonitorGroup].
