package ngat.phase2;
import ngat.phase2.nonpersist.*;

import com.odi.*;
import com.odi.util.*;
import java.lang.reflect.*;
import java.util.*;
import java.io.*;


// Generated by O3J 


public class Moon extends Source implements Serializable {

     // Variables.


     // Constructor.

     public Moon() {this("untitled");}

     public Moon(String name) {
          super(name);
     }

     // Accessors.



     // Descendant Mutators.

     
     // NP -> P Translator.

     public Moon(NPMoon npMoon) {
          super(npMoon);
          Iterator it;
          
          // Recursively call Daughter Translators.

     } // end (NP -> P Translator).
     
     // P -> NP Translator.

     public void stuff(NPMoon npMoon) {
          super.stuff(npMoon);
          Iterator it;
     } // end (P -> NP Translator).
     
     // P -> NP Translator.

     public NPDBObject makeNP() {
          NPMoon npMoon = new NPMoon();
          stuff(npMoon);
          return npMoon;
     } // end (makeNp).


} // end class def [Moon].
