package ngat.phase2;
import ngat.phase2.nonpersist.*;

import jyd.storable.*;
import jyd.collection.*;
import java.lang.reflect.*;
import java.util.*;
import java.io.*;


// Generated by O3J 


public class SpecConfig extends InstrumentConfig implements Serializable {
 
    /** Serial version UID - used to maintain serialization compatibility
     * across modifications of the class's structure.*/    
    private static final long serialVersionUID = 8121000924718541727L;
    
    // Variables.
    
    // Constructor.
    public SpecConfig() {this("untitled");}
    
    public SpecConfig(String name) {
	super(name);
    }
    
    // Clone Constructor.
    public NPDBObject copy() {
	try {
	    return (SpecConfig)clone();
	} catch (CloneNotSupportedException ce) {return null;}
    } // end (copy).
    
} // end class def [SpecConfig].
