package ngat.phase2.nonpersist;

import ngat.phase2.*;
import java.util.*;
import java.io.*;


// Generated by O3J 


public class NPUser extends NPDBObject implements Serializable, Cloneable{

     // Variables.



     /**  the user's email address for contact. */
     protected String email;

    /** Telephone number.*/
    protected String telephone;

    /** Fax number.*/
    protected String fax;

    /** Postal/ZIP code.*/
    protected String postalCode;
       

     /**  organization, department, intitute to which user belongs. */
     protected String organization;


     /**  address field line 1. */
     protected String address1;


     /**  address field line 2. */
     protected String address2;


     /**  address field line 3. */
     protected String address3;


     /**  user's Country. */
     protected String country;


     /**  the user's surname. */
     protected String sname;


     /**  the user's first name. */
     protected String fname;
     protected HashMap npProposals;
     protected HashMap npCoIProposals;

     // Constructor.

     public NPUser() {this("untitled");}

     public NPUser(String name) {
          super(name);
          npProposals = new HashMap();
          npCoIProposals = new HashMap();
     }

     // Accessors.



     /** Sets the  the user's email address for contact .*/
     public void setEmail(String in) { this.email = in;}


     /** Returns the  the user's email address for contact. */
     public String getEmail() { return email;}

    /** Sets the Telephone number.*/
    public void setTelephone(String in) {  this.telephone = in;};

    /** Returns the Telephone number.*/
    public String getTelephone() { return telephone;}
    
    /** Sets the Fax number.*/
    public void setFax(String in) { this.fax = in;};
    
    /** Returns the Fax number.*/
    public String getFax() { return fax;}
    
    /** Sets the Postal/ZIP code.*/
    public void setPostalCode(String in){   this.postalCode = in;};
    
    /** Returns the Postal/ZIP code.*/
    public String getPostalCode() { return postalCode;}


     /** Sets the  organization, department, intitute to which user belongs .*/
     public void setOrganization(String in) { this.organization = in;}


     /** Returns the  organization, department, intitute to which user belongs. */
     public String getOrganization() { return organization;}


     /** Sets the  address field line 1 .*/
     public void setAddress1(String in) { this.address1 = in;}


     /** Returns the  address field line 1. */
     public String getAddress1() { return address1;}


     /** Sets the  address field line 2 .*/
     public void setAddress2(String in) { this.address2 = in;}


     /** Returns the  address field line 2. */
     public String getAddress2() { return address2;}


     /** Sets the  address field line 3 .*/
     public void setAddress3(String in) { this.address3 = in;}


     /** Returns the  address field line 3. */
     public String getAddress3() { return address3;}


     /** Sets the  user's Country .*/
     public void setCountry(String in) { this.country = in;}


     /** Returns the  user's Country. */
     public String getCountry() { return country;}


     /** Sets the  the user's surname .*/
     public void setSname(String in) { this.sname = in;}


     /** Returns the  the user's surname. */
     public String getSname() { return sname;}


     /** Sets the  the user's first name .*/
     public void setFname(String in) { this.fname = in;}


     /** Returns the  the user's first name. */
     public String getFname() { return fname;}


     // Descendant Mutators.

    /** NPClone Constructor.*/  
    public NPDBObject copy() {
	try {
	    return (NPUser)clone();
	} catch (CloneNotSupportedException ce) {return null;}
    } // end (copy).

} // end class def [User].
