/* OFFSET_TT_X_Y_DONE.java */
/* FILE GENERATED BY makeamess - DO NOT EDIT */

/* 
    Copyright 2006, Astrophysics Research Institute, Liverpool John Moores University.

    This file is part of NGAT.

    NGAT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    NGAT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NGAT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
package ngat.message.RCS_BSS;

import ngat.message.base.*;

import java.util.*;
import java.io.*;
/** 
 * On receiving this command the BSS will issue an absolute x/y offset
 * to the tiptilt control mechanism software.
 * <h2>Command Parameters:</h2>
 * <ul>
 * <li><b><i>String</i> instrumentName</b> Inherited from OFFSET_TT.
 * <li><b><i>int </i> tiptiltId</b> Inherited from OFFSET_TT.
 * <li><b><i>float</i> xOffset</b> The absolute offset to move the tiptilt to in arcseconds.
 * <li><b><i>float</i> yOffset</b> The absolute offset to move the tiptilt to in arcseconds.
 * </ul>
 * <h2>Done Parameters:</h2>
 * None
 * @see ngat.message.RCS_BSS.OFFSET_TT
 */ 

public class OFFSET_TT_X_Y_DONE extends OFFSET_TT_DONE implements Serializable
{

/* DONE CONSTANTS */
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id$");

/* DONE ATTRIBUTES */

/* DATTRIBUTE ACCESSORS */

/* CONSTRUCTOR */
	/**
	 * Default constructor for OFFSET_TT_X_Y_DONE.
	 * @param id The message id.
	 */
	public OFFSET_TT_X_Y_DONE(String id)
	{
		super(id);
	}
}
