#!/bin/csh
# $Header: /space/home/eng/cjm/cvs/ngat/scripts/ngat_make_source_tar,v 1.1 2006-05-16 12:07:51 snf Exp $
# Version: $Revision: 1.1 $
# By $Author: snf $
# Make a source tar for Wayne
# This contains:
# 	The Ccs
# 	The DpRt
#	The IcsGUI
#	Associated libraries and test programs
#	Startup scripts
#	Appropriate configuration
# Usage:
# 	ccs_make_source_tar
# dev root directory
set dev_dir 		= "/home/dev"
# dev src directory
set dev_src_dir 	= "${dev_dir}/src"
# directory script was run in
set current_dir		= `pwd`
# temporary directory containing root of deployment tree (which becomes root of tar).
set deployment_dir 	= "/tmp/ccs_source"
# temporary directory containing root of deployment tree (which becomes root of tar).
set deployment_src_dir 	= "/tmp/ccs_source/src"
# temporary directory for deployment temporary files
set deployment_tmp_dir 	= "/tmp/ccs_source/tmp"
# directory to put source tar into
set source_tar_dir = "/home/dev/public_html/ccs/deployment"
# name of tar file
set date_string = `/bin/date +"%Y-%m-%d"`
set source_tar 	= "ccs_source_${date_string}.tar"
#
# Delete any half created deployments
#
if (-d ${deployment_dir}) then
	echo "Deployment directory ${deployment_dir} already exists:clearing..."
	rm -rf ${deployment_dir}
endif
#
# Create directory structure
#
echo "Creating directory structure..."
set dir_count = 0
set dir_list = "${deployment_dir} ${deployment_tmp_dir} ${deployment_src_dir}"
foreach dir ( ${dir_list} )
	mkdir -p ${dir}
	if ($status != 0) then
	   echo "Failed to make directory ${dir}"
	   exit 2
	endif
	@ dir_count ++
end
echo "${dir_count} directories created."
#
# Copy src directories
#
echo "Copying src directories..."
set src_dir_list = "ngat/ccd ngat/fits ngat/math ngat/message/base ngat/message/INST_DP ngat/message/ISS_INST ngat/net ngat/phase2 ngat/sound ngat/swing ngat/util lt/java/dev/lt autobooter/java ccs/java ccs/test dprt/test dprt/java/ngat/dprt ccs_gui/java ccd libdprt/ccs libdprt/jni_general libdprt/rjs libdprt/object ngatastro ngatfits ngatutil "
# ngat/math/test ngat/util/logging dprt/java/ngat/dprt/ccs config sdsu/astro-cam/1.7/ngat
set src_dir_count = 0
foreach src_dir ( ${src_dir_list} )
	echo "src_dir : ${src_dir}"
# check deployment source dir src_dir basedir exists
	set base_dir = `dirname ${deployment_src_dir}/${src_dir}`
	echo "mkdir -p ${base_dir}"
	mkdir -p ${base_dir}
	if ($status != 0) then
	   echo "Failed to make directory ${base_dir}"
	   exit 2
	endif
# copy src_dir to deployment location
	echo "cp -R ${dev_src_dir}/${src_dir} ${base_dir}"
	cp -R ${dev_src_dir}/${src_dir} ${base_dir}
	set cp_status = $status
	if( ${cp_status} != 0 ) then
	    echo "Copy failed: ${dev_src_dir}/${src_dir} to ${base_dir}"
	    exit 3
	endif
# If Makefile exists copy
#	if ( -r ${dev_src_dir}/${src_dir}/Makefile ) then
#		cp ${dev_src_dir}/${src_dir}/Makefile ${deployment_src_dir}/${src_dir}
#		set cp_status = $status
#		if( ${cp_status} != 0 ) then
#		    echo "Copy failed: ${dev_src_dir}/${src_dir}/Makefile to ${deployment_src_dir}/${src_dir}"
#		    exit 3
#		endif
#	endif
# If Makefile.common exists copy
#	if ( -r ${dev_src_dir}/${src_dir}/Makefile.common ) then
#		cp ${dev_src_dir}/${src_dir}/Makefile.common ${deployment_src_dir}/${src_dir}
#		set cp_status = $status
#		if( ${cp_status} != 0 ) then
#		    echo "Copy failed: ${dev_src_dir}/${src_dir}/Makefile.common to ${deployment_src_dir}/${src_dir}"
#		    exit 3
#		endif
#	endif
# copy src_dir/RCS to deployment location
#	if ( -r ${dev_src_dir}/${src_dir}/RCS ) then
#		cp -R ${dev_src_dir}/${src_dir}/RCS ${deployment_src_dir}/${src_dir}
#		set cp_status = $status
#		if( ${cp_status} != 0 ) then
#		    echo "Copy failed: ${dev_src_dir}/${src_dir} to ${deployment_src_dir}/${src_dir}"
#		    exit 3
#		endif
#	endif
end
#
# Tidy deployment temp
#
cd ${deployment_dir}
rm -rf ${deployment_tmp_dir}
#
# Create deployment tar
#
echo "--------------------------"
echo "Creating deployment tar..."
cd ${deployment_dir}
tar cvf ${source_tar_dir}/${source_tar} .
echo "GZipping deployment tar..."
cd ${source_tar_dir}
rm -f ${source_tar}.gz
gzip ${source_tar}
echo "Deployment tar : ${source_tar_dir}/${source_tar}.gz"
rm -rf ${deployment_dir}
#
# $Log: not supported by cvs2svn $
# Revision 1.1  2006/04/11 16:36:13  cjm
# Initial revision
#
#
