/* SET_FOCUS.java */
/* FILE GENERATED BY makeamess - DO NOT EDIT */

/* 
    Copyright 2006, Astrophysics Research Institute, Liverpool John Moores University.

    This file is part of NGAT.

    NGAT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    NGAT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NGAT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
package ngat.message.ISS_INST;

import ngat.message.base.*;

import java.util.*;
import java.io.*;
/**
 * Move the telescope focus to the specified value.  This should
 * be used for overall telescope focusing (TELFOCUS command), not
 * offsets (e.g. filter thickness corrections)
 * <pre>
 * Command Parameters:  float focus (in mm?)
 *
 * Done Parameters:  None
 * </pre>
 */

public class SET_FOCUS extends INST_TO_ISS implements Serializable
{

/* CONSTANTS */
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id$");

/* ATTRIBUTES */
	/**
	 * Attribute focus of type float.
	 */
	private float focus;

/* ATTRIBUTE ACCESSORS */
	/**
	 * Method to set focus.
	 * @param in The value to set, of type float.
	 */
	public void setFocus(float in)
	{
		this.focus=in;
	}

	/**
	 * Method to get focus.
	 * @return The method returns the attribute focus.
	 */
	public float getFocus()
	{
		return this.focus;
	}


/* CONSTRUCTOR */
	/**
	 * Default constructor for SET_FOCUS.
	 * @param id The message id.
	 */
	public SET_FOCUS(String id)
	{
		super(id);
	}
}
