/* TEMPERATURE_ACK.java */
/* FILE GENERATED BY makeamess - DO NOT EDIT */

/* 
    Copyright 2006, Astrophysics Research Institute, Liverpool John Moores University.

    This file is part of NGAT.

    NGAT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    NGAT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NGAT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
package ngat.message.ISS_INST;

import ngat.message.base.*;

import java.util.*;
import java.io.*;
/**
 * During execution of the REBOOT commands some instruments have to take a long time to warm up their
 * CCDs in a safe manner. In these cases an ACK of this class (or a sub-class) will
 * be returned to the client at regular intervals, so the client knows how the reboot is proceeding.
 * It will be returned to the calling process using the Multiple Acknowledge protocol.
 * <h2>Parameters:</h2>
 * <ul>
 * <li><b><i>int</i> timeToComplete</b> (in ms) (inherited from ACK)
 * <li><b><i>double</i> ambientTemperature</b> (The target temperature the CCD has to reach for the REBOOT to succeed)
 * <li><b><i>double</i> currentTemperature</b> (The current temperature of the CCD)
 * </ul>
 */

public class TEMPERATURE_ACK extends ACK implements Serializable
{

/* CONSTANTS */
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id$");

/* ATTRIBUTES */
	/**
	 * Attribute ambientTemperature of type double.
	 */
	private double ambientTemperature;
	/**
	 * Attribute currentTemperature of type double.
	 */
	private double currentTemperature;

/* ATTRIBUTE ACCESSORS */
	/**
	 * Method to set ambientTemperature.
	 * @param in The value to set, of type double.
	 */
	public void setAmbientTemperature(double in)
	{
		this.ambientTemperature=in;
	}

	/**
	 * Method to get ambientTemperature.
	 * @return The method returns the attribute ambientTemperature.
	 */
	public double getAmbientTemperature()
	{
		return this.ambientTemperature;
	}

	/**
	 * Method to set currentTemperature.
	 * @param in The value to set, of type double.
	 */
	public void setCurrentTemperature(double in)
	{
		this.currentTemperature=in;
	}

	/**
	 * Method to get currentTemperature.
	 * @return The method returns the attribute currentTemperature.
	 */
	public double getCurrentTemperature()
	{
		return this.currentTemperature;
	}


/* CONSTRUCTOR */
	/**
	 * Default constructor for TEMPERATURE_ACK.
	 * @param id The message id.
	 */
	public TEMPERATURE_ACK(String id)
	{
		super(id);
	}
}
