/* TIMED_MULTRUNAT_DONE.java */
/* FILE GENERATED BY makeamess - DO NOT EDIT */

/* 
    Copyright 2006, Astrophysics Research Institute, Liverpool John Moores University.

    This file is part of NGAT.

    NGAT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    NGAT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NGAT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
package ngat.message.ISS_INST;

import ngat.message.base.*;

import java.util.*;
import java.io.*;
/** 
 * This command does a series of exposures, each of the same length, starting at a specified time.
 * Exposures are taken until a given total duration has elapsed.
 * <h2>Command Parameters:</h2>
 * <ul>
 * <li><b><i>Date</i> startTime</b> A date representing the time to start taking exposures.
 * <li><b><i>int</i> totalDuration</b> The total length of time to do exposures for, in milliseconds.
 * <li><b><i>int</i> exposureTime</b> (ms) The length of each exposure, in milliseconds.
 * </ul>
 * Some parameters are inherited from EXPOSE.
 * <h2>Done Parameters:</h2>
 * These are inherited from EXPOSE_DONE.
 * @see EXPOSE
 * @see EXPOSE_DONE
 */ 

public class TIMED_MULTRUNAT_DONE extends EXPOSE_DONE implements Serializable
{

/* DONE CONSTANTS */
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id$");

/* DONE ATTRIBUTES */

/* DATTRIBUTE ACCESSORS */

/* CONSTRUCTOR */
	/**
	 * Default constructor for TIMED_MULTRUNAT_DONE.
	 * @param id The message id.
	 */
	public TIMED_MULTRUNAT_DONE(String id)
	{
		super(id);
	}
}
