# $Header: /space/home/eng/cjm/cvs/ngat/eip/Makefile,v 1.1 2013-06-28 10:45:00 cjm Exp $
# $Author: cjm $
# $Id: Makefile,v 1.1 2013-06-28 10:45:00 cjm Exp $
PACKAGENAME    = ngat.eip
PACKAGEDIR     = ngat/eip
JAR_FILE       = ngat_eip.jar

SRCS           = EIPNativeException.java EIPFormatException.java EIPHandle.java EIPPLC.java

DIRS           = test
DIRS_TARGET    = dirs

include $(LT_SRC_HOME)/ngat/Makefile.ngat

#
# $Log: not supported by cvs2svn $
#
