# $Header: /space/home/eng/cjm/cvs/ngat/lamp-df1-arcomess/test/Makefile,v 1.1 2008-03-06 10:47:52 cjm Exp $
# $Id: Makefile,v 1.1 2008-03-06 10:47:52 cjm Exp $
PACKAGENAME    = ngat.lamp.test
PACKAGEDIR     = ngat/lamp/test
JAR_FILE       = ngat_lamp_test.jar

SRCS           = TestLamp.java

include $(LT_SRC_HOME)/ngat/Makefile.ngat


#
# $Log: not supported by cvs2svn $
#
