# $Header: /space/home/eng/cjm/cvs/ngat/astrometry/test/Makefile,v 1.1 2007-09-27 15:36:09 cjm Exp $
PACKAGENAME    = ngat.astrometry.test
PACKAGEDIR     = ngat/astrometry/test
JAR_FILE       = ngat_astrometry_test.jar

SRCS           = TestWCSToolsPixelToWCS.java TestWCSToolsWCSToPixel.java

include $(LT_SRC_HOME)/ngat/Makefile.ngat


#
# $Log: not supported by cvs2svn $
#
