DIRS = base OSS RCS_TCS INST_DP ISS_INST POS_RCS GUI_RCS RCS_BSS
DIRS_TARGET    = dirs


include	$(LT_SRC_HOME)/ngat/Makefile.ngat

checkin:
	echo "checkin not needed for makeamess generated sources."

checkout:
	echo "checkout not needed for makeamess generated sources."

# $Header: /space/home/eng/cjm/cvs/ngat/message/Makefile,v 1.7 2013-03-27 15:03:55 cjm Exp $ 
#
# $Log: not supported by cvs2svn $
# Revision 1.6  2006/05/17 16:29:30  cjm
# Added GUI_RCS.
#
# Revision 1.5  2003/11/14 15:35:05  cjm
# Makefile for ngat.message.
#
# Revision 1.4  2003/03/11 11:45:12  cjm
# Fixed checkin and checkout, so they do not checkin/out the Java sources.
#
# Revision 1.3  2002/10/03 11:21:33  je
# Added POS_RCS to the dirs variable.
#
# Revision 1.2  2002/10/02 11:03:00  je
# Added base, INST_DP and ISS_INST to dirs.
#
# Revision 1.1  2000/12/01 18:39:12  snf
# Initial revision
#
