DIRS = base OSS RCS_TCS INST_DP ISS_INST POS_RCS
DIRS_TARGET    = dirs

checkin:
	echo "checkin not needed for makeamess generated sources."

checkout:
	echo "checkout not needed for makeamess generated sources."

include	$(LT_SRC_HOME)/ngat/Makefile.ngat

# $Header: /space/home/eng/cjm/cvs/ngat/message/Makefile,v 1.4 2003-03-11 11:45:12 cjm Exp $ 
#
# $Log: not supported by cvs2svn $
# Revision 1.3  2002/10/03 11:21:33  je
# Added POS_RCS to the dirs variable.
#
# Revision 1.2  2002/10/02 11:03:00  je
# Added base, INST_DP and ISS_INST to dirs.
#
# Revision 1.1  2000/12/01 18:39:12  snf
# Initial revision
#
