/* ACK.java */
/* FILE GENERATED BY makeamess - DO NOT EDIT */

/* 
    Copyright 2006, Astrophysics Research Institute, Liverpool John Moores University.

    This file is part of NGAT.

    NGAT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    NGAT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NGAT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
package ngat.message.base;

import ngat.message.base.*;

import java.util.*;
import java.io.*;
/**
 * Acknowledge command receipt and return estimated time to complete.
 * There is no associated DONE.
 * <pre>
 * Parameters:  int timeToComplete (in ms)
 * </pre>
 */

public class ACK extends MESSAGE implements Serializable
{

/* CONSTANTS */
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id$");

/* ATTRIBUTES */
	/**
	 * Attribute timeToComplete of type int.
	 */
	private int timeToComplete;

/* ATTRIBUTE ACCESSORS */
	/**
	 * Method to set timeToComplete.
	 * @param in The value to set, of type int.
	 */
	public void setTimeToComplete(int in)
	{
		this.timeToComplete=in;
	}

	/**
	 * Method to get timeToComplete.
	 * @return The method returns the attribute timeToComplete.
	 */
	public int getTimeToComplete()
	{
		return this.timeToComplete;
	}


/* CONSTRUCTOR */
	/**
	 * Default constructor for ACK.
	 * @param id The message id.
	 */
	public ACK(String id)
	{
		super(id);
	}
}
