/* COMMAND_DONE.java */
/* FILE GENERATED BY makeamess - DO NOT EDIT */

/* 
    Copyright 2006, Astrophysics Research Institute, Liverpool John Moores University.

    This file is part of NGAT.

    NGAT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    NGAT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NGAT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
package ngat.message.base;

import ngat.message.base.*;

import java.util.*;
import java.io.*;
/**
 * This comands will never 
 * be sent directly.  Instead a subclass of the
 * command is sent (``XXXX_DONE'') where XXXX represents the
 * command name.  This allows the addition of parameters to the done
 * command.
 * <pre>
 * Done Parameters:
 * boolean successful
 * int errorNum
 * String error String
 * </pre>
 */

public class COMMAND_DONE extends MESSAGE implements Serializable
{

/* CONSTANTS */
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id: COMMAND_DONE.java,v 1.1 2013-07-01 08:56:34 cjm Exp $");

/* ATTRIBUTES */
	/**
	 * Attribute successful of type boolean.
	 */
	private boolean successful;
	/**
	 * Attribute errorNum of type int.
	 */
	private int errorNum;
	/**
	 * Attribute errorString of type String.
	 */
	private String errorString;

/* ATTRIBUTE ACCESSORS */
	/**
	 * Method to set successful.
	 * @param in The value to set, of type boolean.
	 */
	public void setSuccessful(boolean in)
	{
		this.successful=in;
	}

	/**
	 * Method to get successful.
	 * @return The method returns the attribute successful.
	 */
	public boolean getSuccessful()
	{
		return this.successful;
	}

	/**
	 * Method to set errorNum.
	 * @param in The value to set, of type int.
	 */
	public void setErrorNum(int in)
	{
		this.errorNum=in;
	}

	/**
	 * Method to get errorNum.
	 * @return The method returns the attribute errorNum.
	 */
	public int getErrorNum()
	{
		return this.errorNum;
	}

	/**
	 * Method to set errorString.
	 * @param in The value to set, of type String.
	 */
	public void setErrorString(String in)
	{
		this.errorString=in;
	}

	/**
	 * Method to get errorString.
	 * @return The method returns the attribute errorString.
	 */
	public String getErrorString()
	{
		return this.errorString;
	}


/* CONSTRUCTOR */
	/**
	 * Default constructor for COMMAND_DONE.
	 * @param id The message id.
	 */
	public COMMAND_DONE(String id)
	{
		super(id);
	}
}
