/* MESSAGE.java */
/* FILE GENERATED BY makeamess - DO NOT EDIT */

/* 
    Copyright 2006, Astrophysics Research Institute, Liverpool John Moores University.

    This file is part of NGAT.

    NGAT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    NGAT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NGAT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
package ngat.message.base;

import ngat.message.base.*;

import java.util.*;
import java.io.*;
/**
 * Base Message Class
 */

public class MESSAGE implements Serializable
{

/* CONSTANTS */
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id: MESSAGE.java,v 1.1 2013-07-01 08:56:34 cjm Exp $");

/* ATTRIBUTES */
	/**
	 * Attribute id of type String.
	 */
	private String id;

/* ATTRIBUTE ACCESSORS */
	/**
	 * Method to set id.
	 * @param in The value to set, of type String.
	 */
	public void setId(String in)
	{
		this.id=in;
	}

	/**
	 * Method to get id.
	 * @return The method returns the attribute id.
	 */
	public String getId()
	{
		return this.id;
	}


/* CONSTRUCTOR */
	/**
	 * Default constructor for MESSAGE.
	 * @param id The message id.
	 */
	public MESSAGE(String id)
	{
		super();
		this.id = id;
	}
}
