PACKAGENAME    = ngat.serial.arcomess
PACKAGEDIR     = ngat/serial/arcomess
JAR_FILE       = ngat_serial_arcomess.jar

SRCS           = ArcomESSFormatException.java ArcomESSNativeException.java ArcomESS.java

include $(LT_SRC_HOME)/ngat/Makefile.ngat


# $Header: /space/home/eng/cjm/cvs/ngat/serial/arcomess/Makefile,v 1.1 2009-02-04 11:26:46 cjm Exp $ 
#
# $Log: not supported by cvs2svn $
