# $Header: /space/home/eng/cjm/cvs/ngat/dichroic/Makefile,v 1.1 2011-10-12 10:16:54 cjm Exp $
# $Author$
# $Id$
PACKAGENAME    = ngat.dichroic
PACKAGEDIR     = ngat/dichroic
JAR_FILE       = ngat_dichroic.jar

SRCS           = DichroicMoveException.java DichroicException.java Dichroic.java

DIRS           = test
DIRS_TARGET    = dirs

include $(LT_SRC_HOME)/ngat/Makefile.ngat

#
# $Log: not supported by cvs2svn $
#
