# $Header: /space/home/eng/cjm/cvs/ngat/Makefile,v 1.2 2006-11-22 17:05:37 cjm Exp $
# $Revision: 1.2 $

DIRS		= ccd fits math net swing sound util latex message astrometry \
		  phase2 spec instrument ngtcs
DIRS_TARGET 	= dirs

include	Makefile.ngat
#
# $Log: not supported by cvs2svn $
#
