# $Header: /space/home/eng/cjm/cvs/ngat/Makefile,v 1.3 2013-06-28 10:20:33 cjm Exp $
# $Revision: 1.3 $

DIRS		= ccd fits math net swing sound util latex message astrometry \
		  phase2 spec instrument ngtcs serial
DIRS_TARGET 	= dirs

include	Makefile.ngat
#
# $Log: not supported by cvs2svn $
# Revision 1.2  2006/11/22 17:05:37  cjm
# Added RCS tag comments.
#
#
