# $Header: /space/home/eng/cjm/cvs/ngat/df1/test/Makefile,v 1.1 2008-03-06 10:46:56 cjm Exp $
# $Id$
PACKAGENAME    = ngat.df1.test
PACKAGEDIR     = ngat/df1/test
JAR_FILE       = ngat_df1_test.jar

SRCS           = BooleanRead.java BooleanWrite.java FloatRead.java FloatWrite.java IntegerRead.java IntegerWrite.java

include $(LT_SRC_HOME)/ngat/Makefile.ngat


#
# $Log: not supported by cvs2svn $
#
