# $Header: /space/home/eng/cjm/cvs/ngat/dichroic/test/Makefile,v 1.2 2013-06-28 10:43:08 cjm Exp $
# $Id: Makefile,v 1.2 2013-06-28 10:43:08 cjm Exp $
PACKAGENAME    = ngat.dichroic.test
PACKAGEDIR     = ngat/dichroic/test
JAR_FILE       = ngat_dichroic_test.jar

SRCS           = TestDichroic.java SoakTestDichroic.java

include $(LT_SRC_HOME)/ngat/Makefile.ngat


#
# $Log: not supported by cvs2svn $
# Revision 1.1  2011/10/12 10:17:10  cjm
# Initial revision
#
#
