# $Header: /space/home/eng/cjm/cvs/ngat/eip/test/Makefile,v 1.1 2008-10-09 14:14:34 cjm Exp $
# $Id: Makefile,v 1.1 2008-10-09 14:14:34 cjm Exp $
PACKAGENAME    = ngat.eip.test
PACKAGEDIR     = ngat/eip/test
JAR_FILE       = ngat_eip_test.jar

SRCS           = BooleanRead.java IntegerRead.java FloatRead.java BooleanWrite.java FloatWrite.java IntegerWrite.java \
		TwoPlcTest.java PlcReadWriteTest.java

include $(LT_SRC_HOME)/ngat/Makefile.ngat


#
# $Log: not supported by cvs2svn $
#
