# $Header: /space/home/eng/cjm/cvs/ngat/eip/test/Makefile,v 1.2 2008-10-15 13:48:12 cjm Exp $
# $Id: Makefile,v 1.2 2008-10-15 13:48:12 cjm Exp $
PACKAGENAME    = ngat.eip.test
PACKAGEDIR     = ngat/eip/test
JAR_FILE       = ngat_eip_test.jar

SRCS           = BooleanRead.java IntegerRead.java FloatRead.java BooleanWrite.java FloatWrite.java IntegerWrite.java \
		TwoPlcTest.java PlcReadWriteTest.java OnePlcTwoThreadTest.java 

include $(LT_SRC_HOME)/ngat/Makefile.ngat


#
# $Log: not supported by cvs2svn $
# Revision 1.1  2008/10/09 14:14:34  cjm
# Initial revision
#
#
