PACKAGENAME    = ngat.spec.test
PACKAGEDIR     = ngat/spec/test
JAR_FILE       = ngat_spec_test.jar

SRCS           = TestSpectrographFilter.java TestSpectrographCamera.java


include $(LT_SRC_HOME)/ngat/Makefile.ngat

#
# $Header: /space/home/eng/cjm/cvs/ngat/spec/test/Makefile,v 0.5 2004-07-29 14:43:31 cjm Exp $ 
#
# $Log: not supported by cvs2svn $
# Revision 0.4  2004/07/29 14:11:11  cjm
# Jasons version.
#
# Revision 0.3  2002/11/15 14:19:01  je
# Changing Makefile structure
#
# Revision 0.1  2000/10/16 17:39:24  cjm
# initial revision.
#
#
