/* ACQUIRE_DONE.java */
/* FILE GENERATED BY makeamess - DO NOT EDIT */

/* 
    Copyright 2006, Astrophysics Research Institute, Liverpool John Moores University.

    This file is part of NGAT.

    NGAT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    NGAT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NGAT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
package ngat.message.ISS_INST;

import ngat.message.base.*;

import java.util.*;
import java.io.*;
/** 
 * This command causes the instrument to acquire an object which
 * is within its field of view.  It can do this either by
 * (a) moving elements within the instrument, or (b) moving the
 * telescope. 
 * <h2>Command Parameters:</h2>
 * <ul>
 * <li><b><i>int</i> acquisitionMode</b> What sort of acquisition to do, see ngat.phase2.TelescopeConfig#ACQUIRE_MODE_*
 *              One of ACQUIRE_MODE_NONE, ACQUIRE_MODE_BRIGHTEST, ACQUIRE_MODE_WCS.
 * <li><b><i>double</i> RA</b> assumed J2000, radians. The right ascension of the object to acquire.
 * <li><b><i>double</i> dec</b> assumed J2000, radians. The declination of the object to acquire.
 * <li><b><i>double</i> RARate</b> Tracking rate in RA assumed J2000, radians/sec.
 * <li><b><i>double</i> decRate</b> Tracking rate in dec assumed J2000, radians/sec.
 * <li><b><i>long</i> calculationTime</b> Time at which the coordinates and rates were calculated.
 * <li><b><i>double</i> moving</b> True if the target is moving.
 * <li><b><i>int</i> xPixel</b> (pixels) The x pixel position to place the specified RA/Dec on acquisition instrument.
 * <li><b><i>int</i> yPixel</b> (pixels) The y pixel position to place the specified RA/Dec on acquisition instrument.
 * </ul>
 * <h2>Done Parameters:</h2>
 *  None
 * @see ISS_TO_INST
 */ 

public class ACQUIRE_DONE extends ISS_TO_INST_DONE implements Serializable
{

/* DONE CONSTANTS */
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id$");

/* DONE ATTRIBUTES */

/* DATTRIBUTE ACCESSORS */

/* CONSTRUCTOR */
	/**
	 * Default constructor for ACQUIRE_DONE.
	 * @param id The message id.
	 */
	public ACQUIRE_DONE(String id)
	{
		super(id);
	}
}
