/* CALIBRATE_DONE.java */
/* FILE GENERATED BY makeamess - DO NOT EDIT */

/* 
    Copyright 2006, Astrophysics Research Institute, Liverpool John Moores University.

    This file is part of NGAT.

    NGAT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    NGAT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NGAT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
package ngat.message.ISS_INST;

import ngat.message.base.*;

import java.util.*;
import java.io.*;
/** 
 * This command is the superset of all calibrate commands.
 * These are commands that take calibration frames.
 *
 * <pre>
 * Command Parameters:  None
 *
 * Done Parameters:  String filename (generated filename)
 *                   float peakCounts
 *                   float meanCounts  
 * </pre>
 */ 

public class CALIBRATE_DONE extends ISS_TO_INST_DONE implements Serializable
{

/* DONE CONSTANTS */
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id: CALIBRATE_DONE.java,v 1.1 2013-07-01 09:14:14 cjm Exp $");

/* DONE ATTRIBUTES */
	/**
	 * Attribute filename of type String.
	 */
	private String filename;
	/**
	 * Attribute peakCounts of type float.
	 */
	private float peakCounts;
	/**
	 * Attribute meanCounts of type float.
	 */
	private float meanCounts;

/* DATTRIBUTE ACCESSORS */
	/**
	 * Method to set filename.
	 * @param in The value to set, of type String.
	 */
	public void setFilename(String in)
	{
		this.filename=in;
	}

	/**
	 * Method to get filename.
	 * @return The method returns the attribute filename.
	 */
	public String getFilename()
	{
		return this.filename;
	}

	/**
	 * Method to set peakCounts.
	 * @param in The value to set, of type float.
	 */
	public void setPeakCounts(float in)
	{
		this.peakCounts=in;
	}

	/**
	 * Method to get peakCounts.
	 * @return The method returns the attribute peakCounts.
	 */
	public float getPeakCounts()
	{
		return this.peakCounts;
	}

	/**
	 * Method to set meanCounts.
	 * @param in The value to set, of type float.
	 */
	public void setMeanCounts(float in)
	{
		this.meanCounts=in;
	}

	/**
	 * Method to get meanCounts.
	 * @return The method returns the attribute meanCounts.
	 */
	public float getMeanCounts()
	{
		return this.meanCounts;
	}


/* CONSTRUCTOR */
	/**
	 * Default constructor for CALIBRATE_DONE.
	 * @param id The message id.
	 */
	public CALIBRATE_DONE(String id)
	{
		super(id);
	}
}
