/* CONFIG.java */
/* FILE GENERATED BY makeamess - DO NOT EDIT */

/* 
    Copyright 2006, Astrophysics Research Institute, Liverpool John Moores University.

    This file is part of NGAT.

    NGAT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    NGAT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NGAT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
package ngat.message.ISS_INST;

import ngat.message.base.*;

import java.util.*;
import java.io.*;
/**
 * Pass a Java phase II database InstrumentConfig Object to the
 * instrument, and attain that configuration.
 *
 * <pre>
 *
 * Parameters:  InstrumentConfig config 
 *
 * Done Parameters:  None
 * </pre>
 */

public class CONFIG extends SETUP implements Serializable
{

/* CONSTANTS */
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id$");

/* ATTRIBUTES */
	/**
	 * Attribute config of type ngat.phase2.InstrumentConfig.
	 */
	private ngat.phase2.InstrumentConfig config;

/* ATTRIBUTE ACCESSORS */
	/**
	 * Method to set config.
	 * @param in The value to set, of type ngat.phase2.InstrumentConfig.
	 */
	public void setConfig(ngat.phase2.InstrumentConfig in)
	{
		this.config=in;
	}

	/**
	 * Method to get config.
	 * @return The method returns the attribute config.
	 */
	public ngat.phase2.InstrumentConfig getConfig()
	{
		return this.config;
	}


/* CONSTRUCTOR */
	/**
	 * Default constructor for CONFIG.
	 * @param id The message id.
	 */
	public CONFIG(String id)
	{
		super(id);
	}
}
