/* FRODOSPEC_INTERRUPT.java */
/* FILE GENERATED BY makeamess - DO NOT EDIT */

/* 
    Copyright 2006, Astrophysics Research Institute, Liverpool John Moores University.

    This file is part of NGAT.

    NGAT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    NGAT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NGAT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
package ngat.message.ISS_INST;

import ngat.message.base.*;

import java.util.*;
import java.io.*;
/**
 * This command is the superset for <b>some</b> of the interrupt commands for FrodoSpec.
 *
 * <h2>Command Parameters:</h2>
 * <ul>
 * <li><b><i>int</i> arm</b>Which arm to do the exposure on (RED_ARM or BLUE_ARM, see ngat.phase2.FrodoSpecConfig).
 * </ul>
 * @see INTERRUPT
 */

public class FRODOSPEC_INTERRUPT extends INTERRUPT implements Serializable
{

/* CONSTANTS */
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id: FRODOSPEC_INTERRUPT.java,v 1.1 2013-07-01 09:14:14 cjm Exp $");

/* ATTRIBUTES */
	/**
	 * Attribute arm of type int.
	 */
	private int arm;

/* ATTRIBUTE ACCESSORS */
	/**
	 * Method to set arm.
	 * @param in The value to set, of type int.
	 */
	public void setArm(int in)
	{
		this.arm=in;
	}

	/**
	 * Method to get arm.
	 * @return The method returns the attribute arm.
	 */
	public int getArm()
	{
		return this.arm;
	}


/* CONSTRUCTOR */
	/**
	 * Default constructor for FRODOSPEC_INTERRUPT.
	 * @param id The message id.
	 */
	public FRODOSPEC_INTERRUPT(String id)
	{
		super(id);
	}
}
