/* FRODOSPEC_RUNAT.java */
/* FILE GENERATED BY makeamess - DO NOT EDIT */

/* 
    Copyright 2006, Astrophysics Research Institute, Liverpool John Moores University.

    This file is part of NGAT.

    NGAT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    NGAT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NGAT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
package ngat.message.ISS_INST;

import ngat.message.base.*;

import java.util.*;
import java.io.*;
/**
 * Do a single exposure starting at the given (UTC?) time.
 * <pre>
 * Command Parameters: Date startTime = time to start   
 *                    int exposureTime = exposure time in milliseconds
 *
 *
 * </pre>
 */

public class FRODOSPEC_RUNAT extends FRODOSPEC_EXPOSE implements Serializable
{

/* CONSTANTS */
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id: FRODOSPEC_RUNAT.java,v 1.1 2013-07-01 09:14:14 cjm Exp $");

/* ATTRIBUTES */
	/**
	 * Attribute startTime of type java.util.Date.
	 */
	private java.util.Date startTime;
	/**
	 * Attribute exposureTime of type int.
	 */
	private int exposureTime;

/* ATTRIBUTE ACCESSORS */
	/**
	 * Method to set startTime.
	 * @param in The value to set, of type java.util.Date.
	 */
	public void setStartTime(java.util.Date in)
	{
		this.startTime=in;
	}

	/**
	 * Method to get startTime.
	 * @return The method returns the attribute startTime.
	 */
	public java.util.Date getStartTime()
	{
		return this.startTime;
	}

	/**
	 * Method to set exposureTime.
	 * @param in The value to set, of type int.
	 */
	public void setExposureTime(int in)
	{
		this.exposureTime=in;
	}

	/**
	 * Method to get exposureTime.
	 * @return The method returns the attribute exposureTime.
	 */
	public int getExposureTime()
	{
		return this.exposureTime;
	}


/* CONSTRUCTOR */
	/**
	 * Default constructor for FRODOSPEC_RUNAT.
	 * @param id The message id.
	 */
	public FRODOSPEC_RUNAT(String id)
	{
		super(id);
	}
}
