/* FRODOSPEC_ABORT.java */
/* FILE GENERATED BY makeamess - DO NOT EDIT */

/* 
    Copyright 2006, Astrophysics Research Institute, Liverpool John Moores University.

    This file is part of NGAT.

    NGAT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    NGAT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NGAT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
package ngat.message.ISS_INST;

import ngat.message.base.*;

import java.util.*;
import java.io.*;
/**
 * Stop current activity - do not read out.
 * <h2>Command Parameters:</h2>
 * None
 * Inherited from FRODOSPEC_INTERRUPT:
 * <ul>
 * <li><b><i>int</i> arm</b>Which arm to do the exposure on (RED_ARM or BLUE_ARM, see ngat.phase2.FrodoSpecConfig).
 * </ul>
 * <h2>Done Parameters:</h2>
 * None
 * 
 */

public class FRODOSPEC_ABORT extends FRODOSPEC_INTERRUPT implements Serializable
{

/* CONSTANTS */
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id: FRODOSPEC_ABORT.java,v 1.1 2013-07-01 09:14:14 cjm Exp $");

/* ATTRIBUTES */

/* ATTRIBUTE ACCESSORS */

/* CONSTRUCTOR */
	/**
	 * Default constructor for FRODOSPEC_ABORT.
	 * @param id The message id.
	 */
	public FRODOSPEC_ABORT(String id)
	{
		super(id);
	}
}
