/* GET_STATUS_DONE.java */
/* FILE GENERATED BY makeamess - DO NOT EDIT */

/* 
    Copyright 2006, Astrophysics Research Institute, Liverpool John Moores University.

    This file is part of NGAT.

    NGAT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    NGAT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NGAT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
package ngat.message.ISS_INST;

import ngat.message.base.*;

import java.util.*;
import java.io.*;
/** 
 * Command to get some status information from the instrument.
 * <pre>
 * Command Parameters:  int level
 * level takes one of the following values:
 * LEVEL_BASIC
 * LEVEL_INTERMEDIATE
 * LEVEL_FULL
 *
 * Done Parameters: int currentMode
 * This can take one of the following values:
 * MODE_IDLE
 * MODE_CONFIGURING
 * MODE_CLEARING
 * MODE_WAITING_TO_START
 * MODE_EXPOSING
 * MODE_PRE_READOUT
 * MODE_READING_OUT
 * MODE_POST_READOUT
 * MODE_ERROR
 *
 * Hashtable displayInfo (lines of instrument dependant 
 *                        keywords and status strings)
 * The Hashtable has some semi-defined keywords and values. Keywords:
 * KEYWORD_INSTRUMENT_STATUS
 * KEYWORD_DETECTOR_TEMPERATURE_INSTRUMENT_STATUS
 * Values:
 * VALUE_STATUS_OK
 * VALUE_STATUS_WARN
 * VALUE_STATUS_FAIL
 * </pre>
 */ 

public class GET_STATUS_DONE extends INTERRUPT_DONE implements Serializable
{

/* DONE CONSTANTS */
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id: GET_STATUS_DONE.java,v 1.1 2013-07-01 09:14:14 cjm Exp $");
	/**
	 * Constant MODE_IDLE of type int with value 0.
	 */
	public final static int MODE_IDLE = 0;
	/**
	 * Constant MODE_CONFIGURING of type int with value 1.
	 */
	public final static int MODE_CONFIGURING = 1;
	/**
	 * Constant MODE_CLEARING of type int with value 2.
	 */
	public final static int MODE_CLEARING = 2;
	/**
	 * Constant MODE_WAITING_TO_START of type int with value 3.
	 */
	public final static int MODE_WAITING_TO_START = 3;
	/**
	 * Constant MODE_EXPOSING of type int with value 4.
	 */
	public final static int MODE_EXPOSING = 4;
	/**
	 * Constant MODE_PRE_READOUT of type int with value 5.
	 */
	public final static int MODE_PRE_READOUT = 5;
	/**
	 * Constant MODE_READING_OUT of type int with value 6.
	 */
	public final static int MODE_READING_OUT = 6;
	/**
	 * Constant MODE_POST_READOUT of type int with value 7.
	 */
	public final static int MODE_POST_READOUT = 7;
	/**
	 * Constant MODE_ERROR of type int with value 8.
	 */
	public final static int MODE_ERROR = 8;
	/**
	 * Constant KEYWORD_INSTRUMENT_STATUS of type String with value "Instrument.Status".
	 */
	public final static String KEYWORD_INSTRUMENT_STATUS = "Instrument.Status";
	/**
	 * Constant KEYWORD_DETECTOR_TEMPERATURE_INSTRUMENT_STATUS of type String with value "Instrument.Status.Detector.Temperature".
	 */
	public final static String KEYWORD_DETECTOR_TEMPERATURE_INSTRUMENT_STATUS = "Instrument.Status.Detector.Temperature";
	/**
	 * Constant VALUE_STATUS_OK of type String with value "OK".
	 */
	public final static String VALUE_STATUS_OK = "OK";
	/**
	 * Constant VALUE_STATUS_WARN of type String with value "WARN".
	 */
	public final static String VALUE_STATUS_WARN = "WARN";
	/**
	 * Constant VALUE_STATUS_FAIL of type String with value "FAIL".
	 */
	public final static String VALUE_STATUS_FAIL = "FAIL";
	/**
	 * Constant VALUE_STATUS_UNKNOWN of type String with value "UNKNOWN".
	 */
	public final static String VALUE_STATUS_UNKNOWN = "UNKNOWN";

/* DONE ATTRIBUTES */
	/**
	 * Attribute currentMode of type int.
	 */
	private int currentMode;
	/**
	 * Attribute displayInfo of type java.util.Hashtable.
	 */
	private java.util.Hashtable displayInfo;

/* DATTRIBUTE ACCESSORS */
	/**
	 * Method to set currentMode.
	 * @param in The value to set, of type int.
	 */
	public void setCurrentMode(int in)
	{
		this.currentMode=in;
	}

	/**
	 * Method to get currentMode.
	 * @return The method returns the attribute currentMode.
	 */
	public int getCurrentMode()
	{
		return this.currentMode;
	}

	/**
	 * Method to set displayInfo.
	 * @param in The value to set, of type java.util.Hashtable.
	 */
	public void setDisplayInfo(java.util.Hashtable in)
	{
		this.displayInfo=in;
	}

	/**
	 * Method to get displayInfo.
	 * @return The method returns the attribute displayInfo.
	 */
	public java.util.Hashtable getDisplayInfo()
	{
		return this.displayInfo;
	}


/* CONSTRUCTOR */
	/**
	 * Default constructor for GET_STATUS_DONE.
	 * @param id The message id.
	 */
	public GET_STATUS_DONE(String id)
	{
		super(id);
	}
}
