/* GET_STATUS.java */
/* FILE GENERATED BY makeamess - DO NOT EDIT */

/* 
    Copyright 2006, Astrophysics Research Institute, Liverpool John Moores University.

    This file is part of NGAT.

    NGAT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    NGAT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NGAT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
package ngat.message.ISS_INST;

import ngat.message.base.*;

import java.util.*;
import java.io.*;
/**
 * Command to get some status information from the instrument.
 * <pre>
 * Command Parameters:  int level
 * level takes one of the following values:
 * LEVEL_BASIC
 * LEVEL_INTERMEDIATE
 * LEVEL_FULL
 *
 * Done Parameters: int currentMode
 * This can take one of the following values:
 * MODE_IDLE
 * MODE_CONFIGURING
 * MODE_CLEARING
 * MODE_WAITING_TO_START
 * MODE_EXPOSING
 * MODE_PRE_READOUT
 * MODE_READING_OUT
 * MODE_POST_READOUT
 * MODE_ERROR
 *
 * Hashtable displayInfo (lines of instrument dependant 
 *                        keywords and status strings)
 * The Hashtable has some semi-defined keywords and values. Keywords:
 * KEYWORD_INSTRUMENT_STATUS
 * KEYWORD_DETECTOR_TEMPERATURE_INSTRUMENT_STATUS
 * Values:
 * VALUE_STATUS_OK
 * VALUE_STATUS_WARN
 * VALUE_STATUS_FAIL
 * </pre>
 */

public class GET_STATUS extends INTERRUPT implements Serializable
{

/* CONSTANTS */
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id: GET_STATUS.java,v 1.1 2013-07-01 09:14:14 cjm Exp $");
	/**
	 * Constant LEVEL_BASIC of type int with value 0.
	 */
	public final static int LEVEL_BASIC = 0;
	/**
	 * Constant LEVEL_INTERMEDIATE of type int with value 1.
	 */
	public final static int LEVEL_INTERMEDIATE = 1;
	/**
	 * Constant LEVEL_FULL of type int with value 2.
	 */
	public final static int LEVEL_FULL = 2;

/* ATTRIBUTES */
	/**
	 * Attribute level of type int.
	 */
	private int level;

/* ATTRIBUTE ACCESSORS */
	/**
	 * Method to set level.
	 * @param in The value to set, of type int.
	 */
	public void setLevel(int in)
	{
		this.level=in;
	}

	/**
	 * Method to get level.
	 * @return The method returns the attribute level.
	 */
	public int getLevel()
	{
		return this.level;
	}


/* CONSTRUCTOR */
	/**
	 * Default constructor for GET_STATUS.
	 * @param id The message id.
	 */
	public GET_STATUS(String id)
	{
		super(id);
	}
}
