/* LAMPFLAT.java */
/* FILE GENERATED BY makeamess - DO NOT EDIT */

/* 
    Copyright 2006, Astrophysics Research Institute, Liverpool John Moores University.

    This file is part of NGAT.

    NGAT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    NGAT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NGAT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
package ngat.message.ISS_INST;

import ngat.message.base.*;

import java.util.*;
import java.io.*;
/**
 * This command should carry out a LAMPFLAT calibration.
 * The instrument
 * should calculate the appropriate exposure time.
 *
 * <pre>
 *
 * Command Parameters:  String lamp
 * Done Parameters:  inherited from CALIBRATE.
 * </pre>
 */

public class LAMPFLAT extends CALIBRATE implements Serializable
{

/* CONSTANTS */
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id: LAMPFLAT.java,v 1.1 2013-07-01 09:14:14 cjm Exp $");

/* ATTRIBUTES */
	/**
	 * Attribute lamp of type String.
	 */
	private String lamp;

/* ATTRIBUTE ACCESSORS */
	/**
	 * Method to set lamp.
	 * @param in The value to set, of type String.
	 */
	public void setLamp(String in)
	{
		this.lamp=in;
	}

	/**
	 * Method to get lamp.
	 * @return The method returns the attribute lamp.
	 */
	public String getLamp()
	{
		return this.lamp;
	}


/* CONSTRUCTOR */
	/**
	 * Default constructor for LAMPFLAT.
	 * @param id The message id.
	 */
	public LAMPFLAT(String id)
	{
		super(id);
	}
}
