/* OFFSET_RA_DEC.java */
/* FILE GENERATED BY makeamess - DO NOT EDIT */

/* 
    Copyright 2006, Astrophysics Research Institute, Liverpool John Moores University.

    This file is part of NGAT.

    NGAT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    NGAT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NGAT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
package ngat.message.ISS_INST;

import ngat.message.base.*;

import java.util.*;
import java.io.*;
/**
 * Offset the telescope RA and DEC by the amount given.
 * <h2>Command Parameters:</h2>
 * <ul>
 * <li><b><i>float</i> raOffset</b> (in arcsec)
 * <li><b><i>float</i> decOffset</b> (in arcsec)
 * </ul>
 * <h2>Done Parameters:</h2>
 * None
 */

public class OFFSET_RA_DEC extends INST_TO_ISS implements Serializable
{

/* CONSTANTS */
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id$");

/* ATTRIBUTES */
	/**
	 * Attribute raOffset of type float.
	 */
	private float raOffset;
	/**
	 * Attribute decOffset of type float.
	 */
	private float decOffset;

/* ATTRIBUTE ACCESSORS */
	/**
	 * Method to set raOffset.
	 * @param in The value to set, of type float.
	 */
	public void setRaOffset(float in)
	{
		this.raOffset=in;
	}

	/**
	 * Method to get raOffset.
	 * @return The method returns the attribute raOffset.
	 */
	public float getRaOffset()
	{
		return this.raOffset;
	}

	/**
	 * Method to set decOffset.
	 * @param in The value to set, of type float.
	 */
	public void setDecOffset(float in)
	{
		this.decOffset=in;
	}

	/**
	 * Method to get decOffset.
	 * @return The method returns the attribute decOffset.
	 */
	public float getDecOffset()
	{
		return this.decOffset;
	}


/* CONSTRUCTOR */
	/**
	 * Default constructor for OFFSET_RA_DEC.
	 * @param id The message id.
	 */
	public OFFSET_RA_DEC(String id)
	{
		super(id);
	}
}
