/* OFFSET_X_Y.java */
/* FILE GENERATED BY makeamess - DO NOT EDIT */

/* 
    Copyright 2006, Astrophysics Research Institute, Liverpool John Moores University.

    This file is part of NGAT.

    NGAT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    NGAT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NGAT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
package ngat.message.ISS_INST;

import ngat.message.base.*;

import java.util.*;
import java.io.*;
/**
 * Offset the telescope in X and Y (focal plane coords/aperture).
 * <h2>Command Parameters:</h2>
 * <ul>
 * <li><b><i>float</i> xOffset</b> (in arcsec)
 * <li><b><i>float</i> yOffset</b> (in arcsec)
 * <li><b><i>float</i> rotation</b> (in arcsec)
 * </ul>
 * <h2>Done Parameters:</h2>
 * None
 */

public class OFFSET_X_Y extends INST_TO_ISS implements Serializable
{

/* CONSTANTS */
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id$");

/* ATTRIBUTES */
	/**
	 * Attribute xOffset of type float.
	 */
	private float xOffset;
	/**
	 * Attribute yOffset of type float.
	 */
	private float yOffset;
	/**
	 * Attribute rotation of type float.
	 */
	private float rotation;

/* ATTRIBUTE ACCESSORS */
	/**
	 * Method to set xOffset.
	 * @param in The value to set, of type float.
	 */
	public void setXOffset(float in)
	{
		this.xOffset=in;
	}

	/**
	 * Method to get xOffset.
	 * @return The method returns the attribute xOffset.
	 */
	public float getXOffset()
	{
		return this.xOffset;
	}

	/**
	 * Method to set yOffset.
	 * @param in The value to set, of type float.
	 */
	public void setYOffset(float in)
	{
		this.yOffset=in;
	}

	/**
	 * Method to get yOffset.
	 * @return The method returns the attribute yOffset.
	 */
	public float getYOffset()
	{
		return this.yOffset;
	}

	/**
	 * Method to set rotation.
	 * @param in The value to set, of type float.
	 */
	public void setRotation(float in)
	{
		this.rotation=in;
	}

	/**
	 * Method to get rotation.
	 * @return The method returns the attribute rotation.
	 */
	public float getRotation()
	{
		return this.rotation;
	}


/* CONSTRUCTOR */
	/**
	 * Default constructor for OFFSET_X_Y.
	 * @param id The message id.
	 */
	public OFFSET_X_Y(String id)
	{
		super(id);
	}
}
