/* REBOOT.java */
/* FILE GENERATED BY makeamess - DO NOT EDIT */

/* 
    Copyright 2006, Astrophysics Research Institute, Liverpool John Moores University.

    This file is part of NGAT.

    NGAT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    NGAT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NGAT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
package ngat.message.ISS_INST;

import ngat.message.base.*;

import java.util.*;
import java.io.*;
/**
 * This command caused the instrument to ``reboot'', restarting
 * software tasks and leaving the instrument hardware in
 * a defined state.
 *
 * <pre>
 *
 * Command Parameters:  int level
 *
 * where level takes the following values:
 *
 * 1  = REDATUM
 * 2  = SOFTWARE
 * 3  = HARDWARE
 * 4  = POWER_OFF
 *
 * Done Parameters:  THIS COMMAND (UNIQUELY) DOES NOT GENERATE A DONE RESPONSE, except for REDATUM level.
 *
 * </pre>
 */

public class REBOOT extends INTERRUPT implements Serializable
{

/* CONSTANTS */
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id: REBOOT.java,v 1.1 2013-07-01 09:14:14 cjm Exp $");
	/**
	 * Constant LEVEL_REDATUM of type int with value 1.
	 */
	public final static int LEVEL_REDATUM = 1;
	/**
	 * Constant LEVEL_SOFTWARE of type int with value 2.
	 */
	public final static int LEVEL_SOFTWARE = 2;
	/**
	 * Constant LEVEL_HARDWARE of type int with value 3.
	 */
	public final static int LEVEL_HARDWARE = 3;
	/**
	 * Constant LEVEL_POWER_OFF of type int with value 4.
	 */
	public final static int LEVEL_POWER_OFF = 4;

/* ATTRIBUTES */
	/**
	 * Attribute level of type int.
	 */
	private int level;

/* ATTRIBUTE ACCESSORS */
	/**
	 * Method to set level.
	 * @param in The value to set, of type int.
	 */
	public void setLevel(int in)
	{
		this.level=in;
	}

	/**
	 * Method to get level.
	 * @return The method returns the attribute level.
	 */
	public int getLevel()
	{
		return this.level;
	}


/* CONSTRUCTOR */
	/**
	 * Default constructor for REBOOT.
	 * @param id The message id.
	 */
	public REBOOT(String id)
	{
		super(id);
	}
}
