/* TELFOCUS_DONE.java */
/* FILE GENERATED BY makeamess - DO NOT EDIT */

/* 
    Copyright 2006, Astrophysics Research Institute, Liverpool John Moores University.

    This file is part of NGAT.

    NGAT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    NGAT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NGAT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
package ngat.message.ISS_INST;

import ngat.message.base.*;

import java.util.*;
import java.io.*;
/** 
 * This command requires the instrument to issue telescope SET_FOCUS commands
 * in order to attempt to focus the telescope. A frame is taken at several focus positions,
 * and the real time pipeline is run in the frames to measure the f.w.h.m. (seeing) of each frame.
 * A chi-squared fit is applied to the resulting data to find the optimum focus, and best seeing.
 * <h2>Parameters:</h2>
 * <ul>
 * <li><b><i>float</i> startFocus</b> (in mm)
 * <li><b><i>float</i> endFocus</b> (in mm)
 * <li><b><i>float</i> step</b> (in mm)
 * <li><b><i>int</i> exposureTime</b> (in milliseconds)
 * </ul>
 * <h2>Done Parameters:</h2>
 * <ul>
 * <li><b><i>float</i> seeing</b> (fwhm in arcsec)
 * <li><b><i>float</i> currentFocus</b> (in mm)
 * <li><b><i>double</i> a</b> (<b>a</b> term in the equation <i>ax<sup>2</sup>+bx+c</i> generated by chi-squared fit)
 * <li><b><i>double</i> b</b> (<b>b</b> term in the equation <i>ax<sup>2</sup>+bx+c</i> generated by chi-squared fit)
 * <li><b><i>double</i> c</b> (<b>c</b> term in the equation <i>ax<sup>2</sup>+bx+c</i> generated by chi-squared fit)
 * <li><b><i>double</i> chiSquared</b> (The best chi-squared value that resulted in the parameter set.)
 * </ul>
 */ 

public class TELFOCUS_DONE extends SETUP_DONE implements Serializable
{

/* DONE CONSTANTS */
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id$");

/* DONE ATTRIBUTES */
	/**
	 * Attribute seeing of type float.
	 */
	private float seeing;
	/**
	 * Attribute currentFocus of type float.
	 */
	private float currentFocus;
	/**
	 * Attribute a of type double.
	 */
	private double a;
	/**
	 * Attribute b of type double.
	 */
	private double b;
	/**
	 * Attribute c of type double.
	 */
	private double c;
	/**
	 * Attribute chiSquared of type double.
	 */
	private double chiSquared;

/* DATTRIBUTE ACCESSORS */
	/**
	 * Method to set seeing.
	 * @param in The value to set, of type float.
	 */
	public void setSeeing(float in)
	{
		this.seeing=in;
	}

	/**
	 * Method to get seeing.
	 * @return The method returns the attribute seeing.
	 */
	public float getSeeing()
	{
		return this.seeing;
	}

	/**
	 * Method to set currentFocus.
	 * @param in The value to set, of type float.
	 */
	public void setCurrentFocus(float in)
	{
		this.currentFocus=in;
	}

	/**
	 * Method to get currentFocus.
	 * @return The method returns the attribute currentFocus.
	 */
	public float getCurrentFocus()
	{
		return this.currentFocus;
	}

	/**
	 * Method to set a.
	 * @param in The value to set, of type double.
	 */
	public void setA(double in)
	{
		this.a=in;
	}

	/**
	 * Method to get a.
	 * @return The method returns the attribute a.
	 */
	public double getA()
	{
		return this.a;
	}

	/**
	 * Method to set b.
	 * @param in The value to set, of type double.
	 */
	public void setB(double in)
	{
		this.b=in;
	}

	/**
	 * Method to get b.
	 * @return The method returns the attribute b.
	 */
	public double getB()
	{
		return this.b;
	}

	/**
	 * Method to set c.
	 * @param in The value to set, of type double.
	 */
	public void setC(double in)
	{
		this.c=in;
	}

	/**
	 * Method to get c.
	 * @return The method returns the attribute c.
	 */
	public double getC()
	{
		return this.c;
	}

	/**
	 * Method to set chiSquared.
	 * @param in The value to set, of type double.
	 */
	public void setChiSquared(double in)
	{
		this.chiSquared=in;
	}

	/**
	 * Method to get chiSquared.
	 * @return The method returns the attribute chiSquared.
	 */
	public double getChiSquared()
	{
		return this.chiSquared;
	}


/* CONSTRUCTOR */
	/**
	 * Default constructor for TELFOCUS_DONE.
	 * @param id The message id.
	 */
	public TELFOCUS_DONE(String id)
	{
		super(id);
	}
}
