#!/bin/csh

set JAVA_HOME   = /usr/java/j2sdk1.4.2_07 
set JNIINCDIR   = $JAVA_HOME/include/
set JNIMDINCDIR = $JAVA_HOME/include/linux/

set SLA_DIR = /home/dev/src/ngat/astrometry/Linux_sla/lib
set DEST_DIR = /home/dev/bin/lib/i386-linux

cc -Wall -shared -I$JNIINCDIR -I$JNIMDINCDIR -L${SLA_DIR} jslalib.c ${SLA_DIR}/libsla.a -o ${DEST_DIR}/libjslalib.so -lm

