# $Header: /space/home/eng/cjm/cvs/ngat/lamp/test/Makefile,v 1.2 2010-12-09 14:46:12 cjm Exp $
# $Id: Makefile,v 1.2 2010-12-09 14:46:12 cjm Exp $
PACKAGENAME    = ngat.lamp.test
PACKAGEDIR     = ngat/lamp/test
JAR_FILE       = ngat_lamp_test.jar

SRCS           = TestLamp.java TestCalibrationMirror.java

include $(LT_SRC_HOME)/ngat/Makefile.ngat


#
# $Log: not supported by cvs2svn $
# Revision 1.1  2008/03/06 10:47:52  cjm
# Initial revision
#
#
