PACKAGENAME    = ngat.math.test
PACKAGEDIR     = ngat/math/test
JAR_FILE       = ngat_math_test.jar

SRCS           = QuadraticFitTest.java \
		 QuadraticFitTest2.java

include $(LT_SRC_HOME)/ngat/Makefile.ngat


# $Header: /space/home/eng/cjm/cvs/ngat/math/test/Makefile,v 0.8 2013-06-28 13:50:59 cjm Exp $ 
#
# $Log: not supported by cvs2svn $
# Revision 0.7  2002/11/15 13:37:54  je
# *** empty log message ***
#
# Revision 0.6  2002/11/15 13:35:42  je
# As above - co error!
#
# Revision 0.5  2002/11/15 13:35:12  je
# changing Makefile.common to Makefile.ngat
#
# Revision 0.2  2001/08/13 13:13:10  cjm
# Upgraded ngat.OSS.utility. to ngat.util.*.
#
# Revision 0.1  2000/09/01 15:31:21  cjm
# initial revision.
#
#
